# Generated by Django 2.2.4 on 2021-08-13 04:52

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, 
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)
        

def migrate_owners_reverse(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210812_2221'),
    ]

    operations = [
        migrations.RunPython(migrate_owners, reverse_code=migrate_owners_reverse),
    ]
