# Generated by Django 2.2.4 on 2021-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210813_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='flats_owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
