# Generated by Django 2.2.4 on 2021-08-16 07:24

from django.db import migrations
from phonenumbers.phonenumberutil import _raw_input_contains_national_prefix


def migrate_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner=flat.owner, 
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)
        owner.flats.set([flat])
        owner.save()

def migrate_owners_flats_reverse(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210816_1023'),
    ]

    operations = [
        migrations.RunPython(migrate_owners_flats, reverse_code=migrate_owners_flats_reverse),
    ]
