# Generated by Django 2.2.4 on 2021-08-19 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210819_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='who_liked',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='flats_owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
